sudo: required
services: 
  - docker
  
before_install:
  - docker build -t bipulh/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true bipulh/react-test npm test

after_success:
  - docker build -t bipulh/fibonacci-client ./client
  - docker build -t bipulh/fibonacci-server ./server
  - docker build -t bipulh/fibonacci-nginx ./nginx
  - docker build -t bipulh/fibonacci-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  #Push images to docker
  - docker push bipulh/fibonacci-client
  - docker push bipulh/fibonacci-nginx
  - docker push bipulh/fibonacci-server
  - docker push bipulh/fibonacci-worker
  deploy:
   provider: elasticbeanstalk
   region: us-west-1
   app: fibonacci-docker
   env: Fibonaccidocker-env
   bucket_name: elasticbeanstalk-us-west-1-612358015827
   bucket_path: fibonacci-docker
   on:
    branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   